### ISSUE TITLE
TS21 - Comunicar tela de login com serviço de autenticação.

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#102]
### Descrição:
Eu, como desenvolvedor, desejo realizar a comunicação da tela de login com o serviço de autenticação de usuário.

### Critérios de Aceitação
- [x] A API deve estar recebendo os dados da tela de login;
- [x] A API deve estar concedendo acesso somente se os dados estivessem corretos;
- [x] Deve estar utilizando o token do serviço de autenticação.

### Tarefas
- [x] Utilizar o token criado para autenticação;
- [x] Receber os dados dos campos preenchidos na tela de login;
- [x] Conceder acesso ao web client caso os dados estejam corretos.

### Comentários
Nenhum.

**Estimativa de Esforço** : 5 pontos

**Comment by LucasLermen** [comment]
Conexão feita no repositório: https://github.com/botludum/ludum-materiais-frontend
