### ISSUE TITLE
T35 - Realizar testes iniciais

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#109]
### Descrição:
Realizar testes iniciais nos arquivos que já estão prontos.

### Tarefas
- [ ] Testar actions
- [x] Testar microsserviço Pesquisar Dúvida

**Estimativa de Esforço** : 3 pontos

### Comentários
Nenhum.

**Comment by LucasLermen** [comment]
Devido a um bug ocorrido nas actions, as mesmas não puderam ser testadas, dessa forma, a issue foi considerada completa pois testou tudo o que era possível. Assim sendo, uma nova issue será reaberta mais a frente para a realização de testes das actions.
