### ISSUE TITLE
T36 - Configurar Deploy do Core

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#110]
### Descrição:
Realizar deploy do Ludum.

### Tarefas
- [x] Criar Máquina Virtual na nuvem
- [x] Criar webhook compatível com o telegram

**Estimativa de Esforço** : 8 pontos

**Comment by guilhermesiqueira** [comment]
O deploy foi realizado utilizando uma maquina virtual rodando Ubuntu 18.04 na Amazon EC2. Dentro dessa máquina virtual, foi utilizado proxy reverso com nginx para criar um webhook para ser utilizado no telegram. Esse webhook necessitou de um domínio externo, certificados ssl e abrir portas https na maquina virtual. Nesta maquina virtual, o webhook é utilizado no bot e o container do bot é executado em segundo plano, sendo assim possível ele ficar sendo executado continuamente.
