### ISSUE TITLE
T37 - Configurar ferramenta de analise de qualidade do código

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#111]
### Descrição:
Configurar uma ferramenta de análise de qualidade do código para o core do projeto e o microsserviço dúvidas.

### Tarefas
- [x] Mostrar cobertura de testes
- [x] Mostrar manutenibilidade do código

**Comment by guilhermesiqueira** [comment]
No [microsserviço de dúvidas](https://github.com/botludum/Ludum-Duvida) e no core do projeto foi utilizado o [Code Climate](https://codeclimate.com/) para a análise de qualidade do código. Já para a cobertura de testes, as ferramentas utilizadas no microsserviço de dúvidas foi a [Istanbul](https://istanbul.js.org/) integrada ao mocha e à integração contínua no GitLab CI. Já no core, também foi utilizado o GitLab CI para análise dos resultados de cobertura de testes fornecidos pelo [pytest-cov](https://pypi.org/project/pytest-cov/).
