### ISSUE TITLE
T40 - Corrigir issues

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#116]
### Descrição:
Corrigir documentação das issues de acordo com as recomendações da R1.

### Tarefas
- [ ] Atualizar as issues de acordo com o novo escopo;

**Estimativa de Esforço** : 5 pontos

### Comentários
Nenhum.

**Comment by LucasLermen** [comment]
As issues foram corrigidas de acordo com as mudanças feitas no backlog e agora estão adequadas às recomendações feitas na R1.
