### ISSUE TITLE
T41 - Migrar deploy

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#117]
### Descrição:
Migrar deploy para máquina virtual de maior capacidade.

### Tarefas
- [x] Analisar possíveis ferramentas de maior capacidade;
- [x] Analisar recursos fornecidos por cada;
- [x] Fazer migração do deploy.

**Estimativa de Esforço** : 5 pontos

### Comentários
Nenhum.

**Comment by guilhermesiqueira** [comment]
Deploy foi migrado de uma instância t2.micro na Amazon EC2 para uma instância t2.medium, também na Amazon EC2. As configurações são suficientes para manter o bot estável e também utilizar outras tecnologias para o deploy contínuo futuramente.
