### ISSUE TITLE
T42 - Criar Release Notes

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#118]
### Descrição:
Criar template de release notes para as releases geradas.

### Tarefas
- [x] Checar materiais/links de release notes;
- [x] Criar template de release note;
- [x] Criar release note da primeira release do projeto;

**Estimativa de Esforço** : 2 pontos

### Comentários
Nenhum.

**Comment by LucasLermen** [comment]
Criada a versão 0.1.0 do projeto.
