### ISSUE TITLE
T09 - Elaborar NFR

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#12]
### Descrição:
Elaborar NFR no intuito de auxiliar na elicitação de requisitos não funcionais.

### Tarefas
- [x] Elaborar NFR.

**Estimativa de Duração** : 8 pontos 

### Comentários
Nenhum.

**Comment by LucasLermen** [comment]
Documento disponível em: https://fga-eps-mds.github.io/2019.1-Ludum/#/nfr
