### ISSUE TITLE
T46 - Configurar Integração Contínua do Microsserviço de Links e Tutoriais

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#130]
### Descrição:
Realizar as configurações em relação a integração contínua para o microsserviço de links e tutoriais.

### Tarefas
- [x] Realizar espelhamento do repositório [Ludum-Materiais](https://github.com/botludum/Ludum-Materiais) no GitHub no GitLab
- [x] Criar job de teste
- [x] Criar job de build, integrando com o Docker Hub
- [x] Separar imagem uma imagem Docker para branch master e outra para branch development

**Estimativa de Esforço** : 5 pontos

### Comentários
Nenhum.

**Comment by guilhermesiqueira** [comment]
Integração contínua feita utilizando GitLab CI/CD. Repositório espelhado disponível em:
- https://gitlab.com/guilhermesiqueira/ludum-materiais

Imagens do Docker armazenas em:
- https://cloud.docker.com/u/guilhermesiqueira/repository/docker/guilhermesiqueira/ludum-materiais
