### ISSUE TITLE
T49 - Configurar Deploy Contínuo

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#137]
### Descrição:
Configurar deploy contínuo do core do Ludum.

### Tarefas
- [x] Configurar Rancher
- [x] Configurar webhook para o telegram
- [x] Integrar ao GitLab CI/CD

**Estimativa de Esforço** : 13 pontos

**Comment by guilhermesiqueira** [comment]
Para realizar o deploy do core do Ludum foi utilizado Rancher 1.6 dentro de uma droplet rodando Ubuntu 18.04 na Digital Ocean, e para o host do Rancher foi necessário utilizar outra droplet igual na Digital Ocean.
Foi comprado um domínio (por um ano) e utilizado para acessar o Rancher, e esse domínio também foi utilizado para gerar um subdomínio que foi usados como webhook que API do Telegram exige. Para isto, foi adicionado um certificado SSL usando o LetsEncrypt e proxy reverso para Rancher com o [Rancher Active Proxy](https://github.com/adi90x/rancher-active-proxy). 
Para o deploy contínuo foi utilizado [Rancher GitLab Deployment Tool](https://github.com/cdrx/rancher-gitlab-deploy), que serviu para que toda vez que a imagem no Docker Hub for atualizada o container dentro do Rancher seja atualizado também (upgrade).
