### ISSUE TITLE
T50 - Configurar Deploy no Microsserviço de Links e Tutoriais

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#138]
### Descrição:
Realizar deploy do microsserviço de [Materiais](https://github.com/botludum/Ludum-Materiais).

### Tarefas
- [x] Comunicar MongoDB com a aplicação node
- [x] Deploy contínuo na branch master

**Estimativa de Esforço** : 3 pontos

**Comment by guilhermesiqueira** [comment]
Deploy foi realizado no heroku, sendo possível acessá-lo em: https://ludum-materiais.herokuapp.com/
