### ISSUE TITLE
T52 - Construir EVM

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#142]
### Descrição:
Construir gráfico da métrica EVM (Earned Value Management).

### Tarefas
- [x] Consultar artigos sobre a EVM;
- [x] Construir gráfico da EVM.

**Estimativa de Esforço** : 5 pontos

### Comentários
Utilizar os artefatos atualizados na [T51 -Corrigir Backlog do Projeto e Roadmap ](https://github.com/fga-eps-mds/2019.1-Ludum/issues/141).

**Comment by LucasLermen** [comment]
Documento disponível em: 
https://docs.google.com/spreadsheets/d/1hINXazsMr_ZzxUTKmD443DQ9McBCrPj9f5FTxDF5uTc/edit?usp=sharing

**Comment by gabrielademoraes** [comment]
Material consultado no intuito de facilitar a construção da EVM:
> 1. https://34slpa7u66f159hfp1fhl9aur1-wpengine.netdna-ssl.com/wp-content/uploads/2014/11/Earned-Value-Analysis-in-Scrum-Projects.pdf
> 2. http://www.methodsandtools.com/archive/archive.php?id=61
> 3. https://pmstudycircle.com/2012/05/planned-value-pv-earned-value-ev-actual-cost-ac-analysis-in-project-cost-management-2/
> 4. https://www.researchgate.net/publication/316654971_The_Earned_Value_Management_-_A_Measurement_Technique_of_the_Performance_of_the_Costs_and_Labor_in_the_Project
