### ISSUE TITLE
T53 - Criar Modelo do Teste de Usabilidade

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#143]
### Descrição:
Estudar e criar um modelo para realização do teste de usabilidade.

### Tarefas
- [x] Estudar teste de usabilidade;
- [x] Elaborar um modelo para execução do teste.

**Estimativa de Esforço** : 3 pontos

### Comentários
Alguma informação necessária para melhor compreensão.

**Comment by LucasLermen** [comment]
Documento disponível em:
https://fga-eps-mds.github.io/2019.1-Ludum/#/modelo-teste-usabilidade
