### ISSUE TITLE
T56 - Migrar deploy em produção do microsserviço de materiais

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#152]
### Descrição:
Migrar o serviço de deploy em vigor atualmente da branch master no microsserviço de dúvidas para o Rancher.

### Tarefas
- [x] Migrar banco de dados mongo;
- [x] Migrar aplicação Node;
- [x] Conectar ambos.

**Estimativa de Esforço** : 5 pontos

### Comentários
Link para o repositório do microsserviço https://github.com/botludum/Ludum-Materiais.

**Comment by guilhermesiqueira** [comment]
Para produção o deploy foi migrado e está disponível no endereço: `https://produ-o.ludum-materiais.ludumbot.club`
Para homologação o deploy continuará no heroku, estando disponível no endereço: `https://ludum-materiais.herokuapp.com/`
