### ISSUE TITLE
T57 - Configurar deploy contínuo da aplicação ReactJS

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#153]
### Descrição:
Implantar serviço de deploy contínuo no webclient.

### Tarefas
- [x] Comunicação com o backend sendo feita;
- [x] Deve ser possível acessar a página

**Estimativa de Esforço** : 5 pontos

### Comentários
Link para o repositório https://github.com/botludum/ludum-materiais-frontend.

**Comment by guilhermesiqueira** [comment]
Primeiramente foi tentado realizar o deploy no rancher, entretanto, houve problemas de disponibilidade, pois a droplet utilizada não suportou todos os serviços que está sendo rodado dentro dela. Entretanto, o deploy contínuo foi realizado no heroku e está acessível no endereço: 
`https://ludum-materiais-frontend.herokuapp.com/`
