### ISSUE TITLE
T59 - Aplicar Teste de Usabilidade

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#155]
### Descrição:
Aplicar teste de usabilidade a fim de coletar dados de extrema relevância para o desenvolvimento do produto.

### Tarefas
- [ ] Utilizar modelo disponível em https://fga-eps-mds.github.io/2019.1-Ludum/#/modelo-teste-usabilidade;
- [ ] Definir forma de divulgação e aplicação;
- [ ] Aplicar conforme estratégia definida.

**Estimativa de Esforço** : 3 pontos

### Comentários
Nenhum.

**Comment by LucasLermen** [comment]
Documento disponível em: https://docs.google.com/document/d/1doN0CYfy4UbXUx9xHYGa8hk7aaDMwHs1X4lYp2SLJFg/edit
