### ISSUE TITLE
TS24 - Conectar tela de gerenciamento de links à API

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#158]
### Descrição:
Eu, como desenvolvedor, desejo realizar a comunicação da tela de gerenciamento de envio de links com o respectivo endpoint.

### Critérios de Aceitação
- [x ] Os links e seus respectivos detalhes exibidos devem estar de acordo com o Banco de Dados;
- [x ] Ao clicar em aprovar ou reprovar deve estar sendo feita uma requisição do tipo PUT para a API;
- [x ] Deve estar fornecendo feedback acerca da alteração do status;
- [x] O status deve estar sendo alterado no Banco de Dados;
- [x] O status deve estar sendo atualizado na tela.

### Tarefas
- [x] Os links e seus respectivos detalhes exibidos devem ser trazidos do Banco de Dados; 
- [x] Ao clicar em aprovar ou reprovar deve ser feita uma requisição para API;
- [x] A requisição feita deve alterar o status do link no Banco de Dados;
- [x] Quando o status for trocado ele deve ser atualizado na lista exibida.

### Comentários
Nenhum.

**Estimativa de Esforço** : 5 pontos

**Comment by LucasLermen** [comment]
História realizada no seguinte repositório: https://github.com/botludum/ludum-materiais-frontend
