### ISSUE TITLE
T61 - Refatorar Documentação

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#164]
### Descrição:
Corrigir e realizar ajustes na documentação do projeto.

### Tarefas
- [x] Refatorar a EAP visando deixá-la mais detalhada;
- [x] Realizar ajustes no TAP;
- [x] Refatorar Canvas focando mais no produto;
- [x] Refatorar RoadMap da Release 2;
- [x] Refatorar documento de Personalidade do Bot fornecendo mais detalhes;
- [x] Fazer Post Mortem;
- [x] Colocar resultados do teste de usabilidade no GitHub Pages;
- [x] Colocar EVM no GitHub Pages;
- [x] Ajustar diagramas do documento de arquitetura.

**Estimativa de Esforço** : 5 pontos

### Comentários
Nenhum.

**Comment by LucasLermen** [comment]
Documentação toda encontrada no: https://fga-eps-mds.github.io/2019.1-Ludum/#/
