### ISSUE TITLE
S02 - Treinamento de Git

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#2]
### O que será estudado:
Neste treinamento serão contextualizados os comandos básicos do git, bem como o funcionamento do sistema de branches e resolução de conflitos.

### Objetivo:
Nivelar o conhecimento da equipe sobre a ferramenta GitHub, a qual sera utilizada para o controle de versão e desenvolvimento simultâneo do projeto

### Tarefas
- [x] Apresentar comandos básicos;
- [x] Mostrar como funciona o sistema de branches;
- [x] Apresentar um exemplo de resolução de conflitos.

**Estimativa de Duração** : 1 ponto

**Comment by LucasLermen** [comment]
Treinamento realizado no dia 21/03 às 12h30, com todos os integrantes da equipe com exceção do membro João de Assis, que informou à equipe da impossibilidade de sua presença, devido a uma viagem.
