### ISSUE TITLE
T17 - Documentar Sprint 1

### ISSUE THREAD

**Issue by LucasLermen** [fga-eps-mds/2019.1-Ludum#20]
### Descrição:
Criar documentos para planejar e analisar os resultados da <i>sprint</i> a fim de manter a rastreabilidade sobre o andamento do projeto.

### Tarefas 
- [x] Criar documento de planejamento da <i>sprint</i>;
- [x] Criar documento de Resultado da <i>sprint</i>.

**Estimativa de Duração** : 1 ponto 

### Comentários
Nenhum.

**Comment by gabrielademoraes** [comment]
Documento disponível em:
**Planejamento**  - https://fga-eps-mds.github.io/2019.1-Ludum/#/sprint1-planejamento
**Resultado** - https://fga-eps-mds.github.io/2019.1-Ludum/#/sprint1-resultado
