### ISSUE TITLE
T21 - Construir Definição Metodológica

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#25]
### Descrição:
<p align="justify">Documentar metodologia utilizada no projeto.</p>

### Tarefas
- [x] Descrever metodologia.

**Estimativa de Duração** : 3 pontos

### Comentários
Nenhum.

**Comment by LucasLermen** [comment]
Documento disponível em https://fga-eps-mds.github.io/2019.1-Ludum/#/descricao-metodologia
