### ISSUE TITLE
T22 - Definir identidade visual

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#26]
### Descrição:
<p align="justify">Criar identidade visual para o Ludum envolvendo avatar e paleta de cores baseado em sua personalidade.</p>

### Tarefas
- [x] Consultar documento de ![personalidade do bot](https://fga-eps-mds.github.io/2019.1-Ludum/#/personalidade-ludum)
- [x] Definir paleta de cores;
- [x] Definir fonte;
- [x] Definir avatar;

**Estimativa de Duração** : 5 pontos

### Comentários
Alguma informação necessária para melhor compreensão.

**Comment by guilhermesiqueira** [comment]
Identidade visual criada. Logo disponível no [GitHub Pages](https://fga-eps-mds.github.io/2019.1-Ludum/#/), hexadecimais utilizados:
* #d8caed; /* Cor Principal */
* #98819b; /* Cor do titulo da sidebar */
* #eaeaea; /*Cor do Fundo */
* #dcdaea; /*Cor da sidebar */
* #7b7bff; /*Cor do icone da sidebar */
* #63347f; /* Cor do texto da sidebar e botão */

Fontes utilizadas:
* Logo: Sukhumvit Set
* Resto dos textos: .SF NS Display (Apple)
