### ISSUE TITLE
S04 - Estudar Microsserviços

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#27]
### O que será estudado:
<p align="justify">Diversos aspectos e características da arquitetura microsserviços.</p>

### Objetivo:
<p align="justify">Aprofundar os conhecimentos acerca do tema para aplicar corretamente no desenvolvimento do produto.</p>

### Tarefas
- [x] Estudar como é o funcionamento de microsserviços e como eles se comunicam;
- [x] Pesquisar exemplos de soluções em Python.

**Estimativa de Duração** :  5 pontos

**Comment by LucasLermen** [comment]
Materiais utilizados para estudo:

- https://www.tecmundo.com.br/mercado/137802-criacao-aplicativos-microsservicos-flask-facilitada.htm

- https://matruskan.wordpress.com/2016/05/03/uma-cartilha-rapida-sobre-microsservicos/

- https://www.martinfowler.com/microservices/

- http://www.pedromendes.com.br/2016/01/02/microservicos/

- https://www.nginx.com/blog/introduction-to-microservices/

- https://www.nginx.com/learn/microservices/
