### ISSUE TITLE
T23 - Aprimorar Documento de Arquitetura

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#28]
### Descrição:
Desenvolver novas sessões do documento de arquitetura.

### Tarefas
- [x] Colocar template;
- [x] Criar sessão Introdução, dando uma visão ampla no objetivo do produto; 
- [x] Representação da Arquitetura, descrevendo as relações entre os serviços internos e externos;
- [x] Descrever as tecnologias a serem utilizadas;
- [x] Metas e Restrições que a arquitetura apresentam;
- [x] Visão lógica;

**Estimativa de Duração** : 8 pontos

### Comentários
**Links**: 
www.funpar.ufpr.br:8080/rup/process/artifact/ar_sadoc.htm
https://github.com/fga-eps-mds/2017.2-MerendaMais/wiki/Documento-de-Arquitetura

**Comment by LucasLermen** [comment]
Documento disponível em https://fga-eps-mds.github.io/2019.1-Ludum/#/documento-de-arquitetura
