### ISSUE TITLE
T24 - Criar Burndown dos riscos

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#29]
### Descrição:
Criar gráfico para o indicador burndown.

### Tarefas
- [x] Pontuar Riscos
- [x] Construir o Burndown de riscos

**Estimativa de Duração** : 5 pontos

### Comentários
Nenhum.

**Comment by LucasLermen** [comment]
Documento disponível em https://docs.google.com/spreadsheets/d/13Jc5t6x5olyFiFWfq5IFz3rtQa-uf57ZTvQd_05cW8E/edit?usp=sharing
