### ISSUE TITLE
T25 - Documentar Git Flow

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#33]
### Descrição:
Criar documento explicando e detalhando o Git Flow aplicado no projeto.

### Tarefas
- [x] Criar documento;
- [x] Descrever e explicar o Git Flow;
- [x] Colocar no GitHub Pages.

**Estimativa de Duração** : 5 pontos

### Comentários
Alguma informação necessária para melhor compreensão.

**Comment by guilhermesiqueira** [comment]
Documento disponível em: https://fga-eps-mds.github.io/2019.1-Ludum/#/git-flow
