### ISSUE TITLE
T27 - Definir Folha de Estilo

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#35]
### Descrição:
Escolher a folha de estilo que orientará a formulação do código, estabelecendo um padrão e visando aumentar a qualidade de código.

### Tarefas

- [x] Escolher uma folha de estilo;
- [x] Procurar um linter;
- [x] Criar documento.

**Estimativa de Duração** : 3 pontos

### Comentários
Sugestão: https://www.python.org/dev/peps/pep-0008/

**Comment by guilhermesiqueira** [comment]
Folha de estilo adicionada ao GitHub Pages. Ferramenta que será utilizada para analise da sintaxe será  a Flake8.
