### ISSUE TITLE
US05 - Exibir informações sobre a funcionalidade de resolução de dúvidas

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#41]
### Descrição:
Eu, como usuário, desejo compreender mais sobre o tópico de resolução de dúvidas.

### Critérios de Aceitação
- [x] O código deve atender a folha de estilo;
- [x] O conteúdo das mensagens está conforme a [personalidade](https://fga-eps-mds.github.io/2019.1-Ludum/#/personalidade-ludum) definida para ele;
- [x] Nas mensagens é explicado o que a funcionalidade de resolução de dúvidas é capaz de desempenhar de forma clara e prática.

### Tarefas
- [x] O Ludum deve receber o questionamento do usuário acerca da função de resolução de dúvidas;
- [x] O Ludum deve exibir mensagens explicando o que a função de resolução de dúvidas realiza.

### Comentários
Usar como base o protótipo de alta fidelidade.

**Estimativa de Duração** : 5 pontos

**Comment by Wictorgirardi** [comment]
Devido a dificuldade encontrada com o desenvolvimento ligado ao Rasa e seu funcionamento com o Telegram a issue esta sendo realizada agora por 3 pessoas, diferentemente do que foi planejado (2 pessoas).
