### ISSUE TITLE
TS03 - Ajustar endpoint de armazenamento de novos links

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#47]
### Descrição:
Eu, como desenvolvedor, desejo ajustar um endpoint que permite armazenar novos links.

### Critérios de Aceitação
- [x] Os links criados devem estar funcionando apropriadamente;
- [x] Deve estar comunicando com o Banco de Dados implementado;
- [x] As requisições necessárias devem estar implementadas e funcionando corretamente.

### Tarefas 
- [x] Corrigir idioma das rotas;
- [x] Adicionar endpoints relacionados a aprovação dos links.

### Comentários
Nenhum.

**Estimativa de Duração** : 5 pontos

**Comment by LucasLermen** [comment]
A issue foi alterada após a equipe perceber que o que foi solicitado já estava sendo realizado. Dessa forma foram realizados apenas ajustes no endpoint.
Link do endpoint: https://ludum-materiais.herokuapp.com/links/cadastrar
