### ISSUE TITLE
US08 - Informar sobre formas de contribuição com conteúdo

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#48]
### Descrição:
Eu, como usuário, desejo que o Ludum me informe sobre a possibilidade de contribuição com links.

### Critérios de Aceitação
- [x] O código deve atender a folha de estilo;
- [x] O conteúdo das mensagens está conforme a [personalidade](https://fga-eps-mds.github.io/2019.1-Ludum/#/personalidade-ludum) definida para ele;
- [x] O Ludum deve estar explicando como contribuir com links;
- [x] O Ludum deve estar explicando como contribuir com tutoriais;
- [x] O Ludum deve estar introduzindo a funcionalidade;
- [x] O Ludum deve estar exibindo o link para o webclient, após explicar como contribuir;
- [x] O Ludum deve estar explicando que as contribuições passam por avaliações dos administradores;
- [x] Ao final, deve redirecionar ao menu principal.

### Tarefas
- [x] Exibir mensagem introduzindo brevemente a funcionalidade e ressaltando a importância da contribuição do usuário, ex: _"Você é muito importante para deixar o Ludum cada vez melhor e ajudá-lo a cumprir sua missão... Contribua com nossos conteúdos... É muito simples!"_;
- [x] Exibir mensagem explicando como contribuir com links, ex: _"Se você achou um artigo, um vídeo, um fórum, alguma coisa muito legal relacionado a Pygame que ajude outros usuários em seus estudos e gostaria de que o Ludum o compartilhasse, basta cadastrar esse link em nossos materiais"_;
- [x] Exibir mensagem explicando como contribuir com tutoriais, ex: _"Ou se você desenvolveu um jogo e gostaria de ensinar outros usuários como desenvolvê-lo, se tem algum aspecto acerca da Pygame que seria legal ensinar outros usuários, entre outros, não hesite em contribuir com nossos tutoriais..."_;
- [x] Exibir mensagem explicando que todas as contribuições passam por avaliações da equipe administradora;
- [x] Exibir mensagem com o link do webclient, ex: _"Para cadastrar um desses materiais, acesse o endereço: "_;
- [x] Ao final do fluxo, redirecionar para o menu principal;

### Comentários
Nenhum.

**Estimativa de Duração** : 2 pontos

**Comment by lucasgandac** [comment]
Haja vista o fato de que o link disponibilizado para o usuario sera a home do webclient e quando entrar na pagina que ele escolhera se vai contribuir com tutorial ou link, realmente e necessario ter uma mensagem para contribuir com link e outra para contribuir com tutorial ?

**Comment by gabrielademoraes** [comment]
Para evitar mensagens grandes e para ressaltar que há essas duas formas de contribuição, acredito que seria interessante exibir uma mensagem para tutoriais e outra para links e também com intuito de contextualizar o usuário,  e para evitar redundância, o link do webclient pode ser exibido apenas uma vez após as explicações, ao contrário do que estava. Fiz uns ajustes nas tasks tendo em vista compreender melhor esse assunto.

**Comment by gabrielademoraes** [comment]
História realizada (https://github.com/fga-eps-mds/2019.1-Ludum/pull/163) e disponível em: https://github.com/fga-eps-mds/2019.1-Ludum.
