### ISSUE TITLE
US09 - Gerenciar o envio de links

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#50]
### Descrição:
Eu, como administrador, desejo gerenciar o envio de links.

### Critérios de Aceitação
- [x] Deve ter sido criado uma tabela que permita a visualização dos links pendentes e algumas de suas informações (título, tipo e status);
- [x] A tabela deve possuir duas colunas que possibilitem o administrador aceitar ou reprovar um link;
- [x] A tabela deve possuir uma coluna que permita visualizar as informações do link de maneira mais detalhada;
- [x] Exibir modal com detalhes do link ao clicar em "Visualizar".

### Tarefas
- [x] Criar uma tabela para exibir as informações relacionadas ao link  (título, tipo e status);
- [x] Criar uma coluna nessa tabela que permita visualizar todas as informações relacionadas aquele link;
- [x] Criar duas colunas nessa mesma tabela que permita aprovar ou reprovar um link;
- [x] Criar modal para visualizar as informações do link detalhadamente. 

### Comentários
Nenhum.

**Estimativa de Duração** : 5 pontos

**Comment by LucasLermen** [comment]
História realizada no seguinte repositório:  https://github.com/botludum/ludum-materiais-frontend
