### ISSUE TITLE
TS04 - Popular banco de dados com links

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#52]
### Descrição:
Eu, como desenvolvedor, desejo popular o banco com links interessantes.

### Critérios de Aceitação
- [x] O Banco de Dados deve estar guardando os links interessantes relacionados ao tema.

### Tarefas
- [x] Coletar links relevantes relacionados a PyGame;
- [x] Popular o banco com os links selecionados.

### Comentários
Nenhum.

**Estimativa de Duração** : 3 pontos

**Comment by LucasLermen** [comment]
Banco populado com links úteis. É possível visualizar os links no seguinte endereço: https://ludum-materiais.herokuapp.com/api/links/cadastrar

**Comment by gabrielademoraes** [comment]
Com a maturidade e aprendizado adquirido posteriormente a realização da issue foi percebido que havia uma melhor forma para realização dessa tarefa, sendo assim, a issue será reaberta.

**Comment by guilhermesiqueira** [comment]
Banco de dados populado com links assim quando o servidor é colocado pra rodar. Para visualizar a solução, acesse o repositório [Ludum Materiais](https://github.com/botludum/Ludum-Materiais)
