### ISSUE TITLE
US11 - Visualizar FAQ

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#56]
### Descrição:
Eu, como usuário, desejo visualizar as perguntas feitas com mais frequência.

### Critérios de Aceitação
- [ ] O código deve atender a folha de estilo;
- [ ] O conteúdo das mensagens está conforme a [personalidade](https://fga-eps-mds.github.io/2019.1-Ludum/#/personalidade-ludum) definida para ele;
- [ ] O Ludum deve mostrar ao usuário as perguntas mais frequentes acerca do PyGame;
- [ ] O Ludum deve estar recebendo corretamente a escolha do usuário e mostrando a respectiva resposta.

### Tarefas
- [ ] O Ludum deve exibir uma mensagem com as perguntas mais frequentes;
- [ ] O Ludum deve perguntar se alguma dessas perguntas é a que o usuário procura;
- [ ] O Ludum deve ler a escolha do usuário;
- [ ] O Ludum deve mostrar a resposta da pergunta selecionada, se estiver presente no FAQ.

### Comentários
Links interessantes: https://www.pygame.org/wiki/FrequentlyAskedQuestions.

**Estimativa de Duração** : 3 pontos

**Comment by lucasgandac** [comment]
Antes de começar o codigo, posso salvar as melhores perguntas num arquivo .md ?

**Comment by gabrielademoraes** [comment]
Pode fazer um .md na pasta Docs.
