### ISSUE TITLE
TS08 - Criar jogo de baixa complexidade

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#61]
### Descrição:
Eu, como desenvolvedor, desejo criar um jogo de baixa complexidade para elaborar o tutorial

### Critérios de Aceitação
- [x] Jogo possui baixa complexidade;
- [x] Jogo funcionando conforme regras e objetivos;
- [x] Código comentado;
- [x] Código seguindo boas práticas de programação.

### Tarefas
- [x] Criar jogo de baixa complexidade - Pong;
- [x] Fazer tutorial;
- [x] Comentar o código;
- [x] Utilizar boas práticas de programação;
- [x] Fazer rascunho do tutorial em forma de documento.

### Comentários
Recomendação: https://wiki.python.org.br/PyGame.

**Estimativa de Duração** : 5 pontos

**Comment by lucasgandac** [comment]
Como a tarefa sera fazer o rascunho em forma de documento, como funcionara os commits ?

**Comment by gabrielademoraes** [comment]
Esse documento deve ser feito em formato .md na pasta docs. Assim, a política de commits pode ser aplicada de forma habitual.
