### ISSUE TITLE
TS09 - Criar jogo com maior complexidade

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#62]
### Descrição:
Eu, como desenvolvedor, desejo criar um jogo de complexidade um pouco mais alta para elaborar o tutorial.

### Critérios de Aceitação
- [x] Jogo possui maior complexidade;
- [x] Jogo funcionando conforme regras e objetivos;
- [x] Código comentado;
- [x] Código seguindo boas práticas de programação

### Tarefas
- [x] Definir qual jogo será feito;
- [x] Criar jogo de maior complexidade;
- [x] Fazer tutorial;
- [x] Comentar o código;
- [x] Utilizar boas práticas de programação;
- [x] Fazer rascunho do tutorial em forma de documento.

### Comentários
Recomendação: https://wiki.python.org.br/PyGame.

**Estimativa de Duração** : 8 pontos

**Comment by thallysbraz** [comment]
a branch TS09 crio a partir da devel ou docs?

**Comment by gabrielademoraes** [comment]
A branch TS09 deve ser criada a partir da <b>development</b>.

**Comment by thallysbraz** [comment]
Pode usar imagens no tutorial, para mostrar como está ficando o código?

**Comment by LucasLermen** [comment]
> Pode usar imagens no tutorial, para mostrar como está ficando o código?

Isso será decidido mais a frente, mas por enquanto faça com imagens.
