### ISSUE TITLE
US14 - Aprender a criar um jogo de baixa complexidade

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#63]
### Descrição:
Eu, como usuário, desejo aprender a criar um jogo de baixa complexidade.

### Critérios de Aceitação
- [x] O código deve atender a folha de estilo;
- [ ] O conteúdo das mensagens está conforme a [personalidade](https://fga-eps-mds.github.io/2019.1-Ludum/#/personalidade-ludum) definida para ele;
- [x] O Ludum antes de iniciar o tutorial deve estar notificando o usuário sobre a importância da seção de **Ambiente**;
- [x] O Ludum deve estar ensinando o usuário a criar um jogo de baixa complexidade;
- [x] O Ludum deve estar contextualizando o usuário acerca do jogo a ser desenvolvido;
- [x] O Ludum deve estar respeitando o ritmo do usuário em relação ao passo a passo;
- [x] As mensagens exibidas não podem estar longas;
- [x] Os exemplos de código devem estar claros.

### Tarefas
- [x] Antes de iniciar o tutorial, o Ludum deve informar o usuário acerca da importância de conferir a seção de **Ambiente** antes de iniciar um tutorial;
- [x] O Ludum deve contextualizar o usuário sobre o jogo que será implementado (regras, curiosidades, entre outros);
- [x] O Ludum deve ensinar passo a passo como desenvolver o jogo por meio de mensagens e exemplos de código;
- [x] Nos intervalos entre os passos, o Ludum deve pedir a confirmação do usuário para continuação do tutorial; 

### Comentários
Seguir tutorial realizado na [TS08 - Criar jogo de baixa complexidade](https://github.com/fga-eps-mds/2019.1-Ludum/issues/61).

**Estimativa de Duração** : 13 pontos

**Comment by Wictorgirardi** [comment]
Como deveria ser feita a apresentação dos códigos dos tutoriais? Por meio de uma imagem para o usuário ou por uma mensagem com o código?
