### ISSUE TITLE
US15 - Aprender a criar um jogo de maior complexidade 

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#64]
### Descrição:
Eu, como usuário, desejo aprender a criar um jogo de complexidade um pouco mais alta.

### Critérios de Aceitação
- [ ] O código deve atender a folha de estilo;
- [ ] O conteúdo das mensagens está conforme a [personalidade](https://fga-eps-mds.github.io/2019.1-Ludum/#/personalidade-ludum) definida para ele;
- [ ] O Ludum antes de iniciar o tutorial deve estar notificando o usuário sobre a importância da seção de **Ambiente**;
- [ ] O Ludum deve estar ensinando o usuário a criar um jogo de maior complexidade;
- [ ] O Ludum deve estar contextualizando o usuário acerca do jogo a ser desenvolvido;
- [ ] O Ludum deve estar respeitando o ritmo do usuário em relação ao passo a passo;
- [ ] As mensagens exibidas não podem estar longas;
- [ ] Os exemplos de código devem estar claros.

### Tarefas
- [ ] Antes de iniciar o tutorial, o Ludum deve informar o usuário acerca da importância de conferir a seção de **Ambiente** antes de iniciar um tutorial;
- [ ] O Ludum deve contextualizar o usuário sobre o jogo que será implementado (regras, curiosidades, entre outros);
- [ ] O Ludum deve ensinar passo a passo como desenvolver o jogo por meio de mensagens e exemplos de código;
- [ ] Nos intervalos entre os passos, o Ludum deve pedir a confirmação do usuário para continuação do tutorial; 

### Comentários
Seguir tutorial realizado na [TS09 - Criar jogo com maior complexidade](https://github.com/fga-eps-mds/2019.1-Ludum/issues/62).

**Estimativa de Duração** : 13 pontos

**Comment by thallysbraz** [comment]
crio a branch como Feature/US15?

**Comment by guilhermesiqueira** [comment]
> crio a branch como Feature/US15?

Isso!
