### ISSUE TITLE
T31 - Criar Manual da Identidade Visual(MIV)

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#71]
### Descrição:
Criar o Manual da Identidade Visual a fim de documentar os diversos aspectos relacionados ao desenvolvimento da Identidade Visual.

### Tarefas
- [x] Criar apresentação;
- [x] Documentar na apresentação o tópico Personalidade;
- [x] Documentar na apresentação o tópico Logo;
- [x] Documentar na apresentação o tópico Assinatura;
- [x] Documentar na apresentação o tópico Paleta de Cores;
- [x] Documentar na apresentação o tópico Tipografia;

**Estimativa** : 3 pontos

### Comentários
Seguir definição da Identidade Visual conforme a issue [Definir identidade visual](https://github.com/fga-eps-mds/2019.1-Ludum/issues/26).

**Comment by guilhermesiqueira** [comment]
Manual criado e disponível em: https://fga-eps-mds.github.io/2019.1-Ludum/#/miv
