### ISSUE TITLE
T33 - Finalizar documento de arquitetura

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#73]
### Descrição:
Desenvolver tópicos faltantes do documento de arquitetura.

### Tarefas
- [x] Diagrama de Relações;
- [x] Visão de implementação;
- [x] Visão de implantação;
- [x] Visão de dados;
- [x] Corrigir erros de português:

**Estimativa** : 8 pontos

### Comentários
Nenhum.

**Comment by LucasLermen** [comment]
Documento disponível em https://fga-eps-mds.github.io/2019.1-Ludum/#/documento-de-arquitetura. As seções citadas nas _tasks_ foram refatoradas e diversos diagramas, como implantação e implementação foram criados.
