### ISSUE TITLE
TS10 - Modelar o banco de dados do microsserviço de links e tutoriais

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#86]
### Descrição:
Eu, como desenvolvedor, desejo modelar o banco de dados do microsserviço de materiais, links e tutoriais.

### Critérios de Aceitação
- [x] Possuir documentação da modelagem. (Modelo lógico)
- [x] A modelagem deve atender as necessidades da aplicação

### Tarefas
- [x] Fazer modelo lógico do banco de dados do microsserviço de links e tutoriais.

### Comentários
Nenhum.

**Estimativa de Esforço** : 3 pontos

**Comment by LucasLermen** [comment]
Diagrama do banco de dados não relacional do microsserviço:  

![bd-microsserviço-materiais](https://user-images.githubusercontent.com/23313535/57895937-86f6fc80-7824-11e9-99e6-4278441cbf37.png)
