### ISSUE TITLE
TS13 - Ajustar endpoint de armazenamento de novos tutoriais

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#89]
### Descrição:
Eu, como desenvolvedor, desejo ajustar um endpoint que permite armazenar novos tutoriais.

### Critérios de Aceitação
- [x] Os links criados devem estar funcionando apropriadamente;
- [x] Deve estar comunicando com o Banco de Dados implementado;
- [x] As requisições necessárias devem estar implementadas e funcionando corretamente.

### Tarefas 
- [x] Corrigir idioma das rotas.

### Comentários
Nenhum.

**Estimativa de Esforço** : 5 pontos

**Comment by LucasLermen** [comment]
A issue foi alterada após a equipe perceber que o que foi solicitado já estava sendo realizado. Dessa forma foram realizados apenas ajustes no endpoint.
Link do endpoint: https://ludum-materiais.herokuapp.com/tutoriais/cadastrar
