### ISSUE TITLE
TS15 - Criar endpoint para acesso aos tutoriais

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#94]
### Descrição:
Eu, como desenvolvedor, desejo criar um endpoint para acesso aos tutoriais.

### Critérios de Aceitação
- [x] Os links criados devem estar funcionando apropriadamente;
- [x] Deve estar comunicando com o Banco de Dados implementado;
- [x] As requisições necessárias devem estar implementadas e funcionando corretamente.

### Tarefas
- [x] Checar a modelagem e implementação do banco de dados - [TS10](https://github.com/fga-eps-mds/2019.1-Ludum/issues/86) e [TS11](https://github.com/fga-eps-mds/2019.1-Ludum/issues/87);
- [x] Definir quais tipos de requisição serão necessárias para esse endpoint;
- [x] Conectar com o banco de dados implementado;
- [x] Implementar as requisições necessárias.

### Comentários
Link para o repositório do microsserviço https://github.com/botludum/Ludum-Materiais.

**Estimativa de Esforço** : 5 pontos

**Comment by LucasPenido** [comment]
Para completar algumas tasks, é necessário adicionar uma coluna "status" ao Banco de Dados para tornar possível o controle de aprovação. Posso adicionar esta coluna na model de tutoriais?

**Comment by LucasLermen** [comment]
> Para completar algumas tasks, é necessário adicionar uma coluna "status" ao Banco de Dados para tornar possível o controle de aprovação. Posso adicionar esta coluna na model de tutoriais?

Após uma análise da equipe, foi definido que essa coluna extra seria realmente importantante para o funcionamento do microsserviço. Pode adicionar.

**Comment by LucasPenido** [comment]
Endpoint criado, disponível no repositório: https://github.com/botludum/Ludum-Materiais.
Endereços do endpoint:
http://localhost:8080/api/tutoriais
http://localhost:8080/api/newtutorial
http://localhost:8080/api//tutoriaisAprovados/:status
http://localhost:8080/api/tutoriaisPendentes
http://localhost:8080/api/tutorial/:id/:aprovacao
