### ISSUE TITLE
TS17 - Modelar BD do Microsserviço de conexão com StackOverflow

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#97]
### Descrição:
Eu, como desenvolvedor, desejo modelar o banco de dados do microsserviço de conexão com o StackOverflow.

### Critérios de Aceitação
- [x] Possuir documentação da modelagem. (Modelo lógico)
- [x] A modelagem deve atender as necessidades da aplicação

### Tarefas
- [x] Fazer modelo lógico do banco de dados do microsserviço de conexão com o StackOverflow;
- [x] Adicionar no documento de arquitetura.

### Comentários
Nenhum.

**Estimativa de Esforço** : 3 pontos

**Comment by guilhermesiqueira** [comment]
Diagrama do banco de dados não relacional do microsserviço:

 ![Untitled Diagram](https://user-images.githubusercontent.com/30915713/56871306-4c9efa00-69f2-11e9-845b-e5bf801ea4c6.png)
