### ISSUE TITLE
TS18 - Implementar Banco de Dados do Microsserviço de Conexão com StackOverflow

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#98]
### Descrição:
Eu, como desenvolvedor, desejo implementar o banco de dados do microsserviço de conexão com StackOverflow.

### Critérios de Aceitação
- [x] O Banco de Dados deve estar implementado de acordo com a modelagem;
- [x] Deve estar conectado com o microsserviço.

### Tarefas 
- [x] Consultar documentação da modelagem do Banco de Dados do microsserviço de conexão com StackOverflow;
- [x] Implementar Banco de Dados conforme modelagem e o que está acordado no [Documento de Arquitetura](https://fga-eps-mds.github.io/2019.1-Ludum/#/documento-de-arquitetura)

### Comentários
Nenhum.

**Estimativa de Esforço** : 5 pontos

**Comment by guilhermesiqueira** [comment]
Banco de dados implementado, disponível no repositório: https://github.com/botludum/Ludum-Duvida

Endereço do deploy da api: https://ludum-duvidas.herokuapp.com
