### ISSUE TITLE
US20 - Visualizar tutoriais da comunidade

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#99]
### Descrição:
Eu, como usuário, desejo visualizar todos os tutoriais da comunidade disponíveis.

### Critérios de Aceitação
- [x] O código deve atender a folha de estilo;
- [x] O conteúdo das mensagens está conforme a [personalidade](https://fga-eps-mds.github.io/2019.1-Ludum/#/personalidade-ludum) definida para ele;
- [x] A requisição GET deve estar trazendo todos os tutoriais aprovados;
- [x] O Ludum deve estar exibindo uma lista numerada com todos os tutoriais disponíveis;
- [x] O Usuário deve estar conseguindo escolher um tutorial por seu respectivo número;
- [x] A escolha do usuário deve estar sendo validada.

### Tarefas
- [x] Fazer uma requisição do tipo GET para o microsserviço de Materiais e recuperar todos os tutoriais aprovados;
- [x] Ao clicar em "Tutoriais da comunidade", o Ludum deve exibir uma lista numerada com os nomes dos tutoriais disponíveis;
- [x] O Usuário deve escolher um tutorial disponível pelo seu respectivo número;
- [x] Validar se o número digitado pelo usuário corresponde a um tutorial disponível.

### Comentários
Nenhum.

**Estimativa de Esforço** : 5 pontos

**Comment by Wictorgirardi** [comment]
As duas ultimas tarefas: O Usuário deve escolher um tutorial disponível pelo seu respectivo número e Validar se o número digitado pelo usuário corresponde a um tutorial disponível fazem parte da US22, portanto não foram executadas nessa US.

**Comment by Wictorgirardi** [comment]
Peço Desculpa também pelo atraso, Devido ao bug grave do bot que impossibilitou o desenvolvimento nesses últimos dias houve esse grande atraso na entrega

**Comment by Wictorgirardi** [comment]
História realizada (#170 ) e disponível em: https://github.com/fga-eps-mds/2019.1-Ludum.
